### ISSUE TITLE
App is restarting randomly.

### ISSUE THREAD

**Issue by yadavshivam3000** [Vidyo/helloworld-vidyo.io-android#13] opened 2019-02-20 11:06 UTC
I am facing a issue whenever I finished calling then app crashed and new process starts randomly.

**Comment by pfuternik** [comment] 2019-02-20 16:23
Hello, are you running this project exactly as is or are there any modifications? Can you insert a breakpoint and determine where the crash is occurring?

**Comment by yadavshivam3000** [comment] 2019-02-21 13:04
Hi,
I solved the issue. Issue was generating calling of disable method without calling disconnect method of connector.

But the documentation didn't say it . Never I get any logs in logcat for the crash so it was hard to find the issue.
Anyways thanks for your support.

**Comment by pfuternik** [comment] 2019-02-21 14:14
Glad you found the root cause. I will then close this issue.

**Closed by pfuternik** 2019-02-21 14:14 UTC
